Repository kuzzleio/sdk-javascript, pull requests merged in 2018-12, with the labels that each got.

#342 Release 5.0.14
  package-lock.json
  package.json
  src/MemoryStorage.js
  src/Room.js
  test/MemoryStorage/methods.test.js
  test/Room/methods.test.js
Labels: release

#341 Expose protocols classes
  CHANGELOG.md
  README.md
  features/support/world.js
  index.js
  package-lock.json
  src/Kuzzle.js
  src/controllers/realtime/room.js
  src/networkWrapper/index.js
  src/protocols/abstract/common.js
  src/protocols/abstract/realtime.js
  src/protocols/http.js
  src/protocols/index.js
  src/protocols/socketio.js
  src/protocols/websocket.js
  test/controllers/realtime/room.test.js
  test/kuzzle/connect.test.js
  test/kuzzle/constructor.test.js
  test/kuzzle/getters.test.js
  test/kuzzle/listenersManagement.test.js
  test/kuzzle/protocol.test.js
  test/kuzzle/query.test.js
  test/kuzzle/queue.test.js
  test/kuzzle/setters.test.js
  test/mocks/protocol.mock.js
  test/network/networkWrapper.test.js
  test/network/offlineQueue.test.js
  test/protocol/http.test.js
  test/protocol/query.test.js
  test/protocol/socketio.test.js
  test/protocol/websocket.test.js
Labels: changelog:breaking-changes

#345 Fix 343 unhandled rejection on connect
  src/protocols/abstract/realtime.js
  test/protocol/websocket.test.js
Labels: 6-dev, changelog:bug-fixes

#346 get mapping on aliased index
  src/CollectionMapping.js
  test/CollectionMapping/methods.test.js
Labels: changelog:bug-fixes

#351 Release 6.0.0-beta-4
  README.md
  features/steps/document.js
  package-lock.json
  package.json
  src/controllers/document.js
  src/protocols/abstract/realtime.js
  test/controllers/document.test.js
  test/protocol/websocket.test.js
  webpack.config.js
Labels: release

#350 Have host param mandatory for protocols
  README.md
  features/support/world.js
  index.js
  src/protocols/abstract/common.js
  src/protocols/abstract/realtime.js
  src/protocols/http.js
  src/protocols/index.js
  src/protocols/socketio.js
  src/protocols/websocket.js
  test/kuzzle/connect.test.js
  test/kuzzle/constructor.test.js
  test/kuzzle/getters.test.js
  test/kuzzle/protocol.test.js
  test/kuzzle/query.test.js
  test/kuzzle/queue.test.js
  test/kuzzle/setters.test.js
  test/mocks/protocol.mock.js
  test/protocol/http.test.js
  test/protocol/socketio.test.js
  test/protocol/websocket.test.js
Labels: 6-dev, changelog:enhancements
