Repository kuzzleio/sdk-javascript, pull requests merged in 2018-03, with the labels that each got.

#271 HTTP Protocol suport
  package.json
  src/Collection.js
  src/Kuzzle.js
  src/networkWrapper/index.js
  src/networkWrapper/protocols/abstract/common.js
  src/networkWrapper/protocols/abstract/realtime.js
  src/networkWrapper/protocols/http.js
  src/networkWrapper/protocols/socketio.js
  src/networkWrapper/protocols/websocket.js
  test/.eslintrc.json
  test/kuzzle/connect.test.js
  test/kuzzle/methods.test.js
  test/mocks/networkWrapper.mock.js
  test/network/http.test.js
  test/network/offlineQueue.test.js
  test/network/query.test.js
  test/network/socketio.test.js
  test/network/websocket.test.js
Labels: changelog:new-features

#286 volatile data can also be null
  package-lock.json
  src/networkWrapper/protocols/abstract/realtime.js
Labels: changelog:bug-fixes

#288 SDK refactor: Auth controller
  src/Auth.js
  src/Kuzzle.js
  src/networkWrapper/protocols/socketio.js
  src/security/SecurityDocument.js
  test/Auth/methods.test.js
  test/kuzzle/constructor.test.js
  test/kuzzle/login.test.js
  test/kuzzle/methods.test.js
  test/kuzzle/query.test.js
  test/mocks/kuzzle.mock.js
  test/security/kuzzleSecurity/rightsMethods.test.js
  webpack.config.js
Labels: changelog:breaking-changes
