Repository kuzzleio/sdk-javascript, pull requests merged in 2018-10, with the labels that each got.

#318 KZL-547 - Update validateSpecifications signature to take index and collection
  src/controllers/collection.js
  test/controllers/collection.test.js
Labels: changelog:enhancements

#320 Fix return value for index#list and index#mDelete
  src/controllers/index.js
  test/controllers/index.test.js
Labels: 6-dev, changelog:bug-fixes

#323 SearchResult - mark internal properties as pseudo-private + aggregation support
  package-lock.json
  src/controllers/searchResult/base.js
  src/controllers/searchResult/document.js
  src/controllers/searchResult/profile.js
  src/controllers/searchResult/role.js
  src/controllers/searchResult/specifications.js
  src/controllers/searchResult/user.js
  test/controllers/collection.test.js
  test/controllers/document.test.js
  test/controllers/searchResult/document.test.js
  test/controllers/searchResult/profile.test.js
  test/controllers/searchResult/role.test.js
  test/controllers/searchResult/specifications.test.js
  test/controllers/searchResult/user.test.js
  test/controllers/security.test.js
Labels: changelog:enhancements

#328 Fix realtime publish return
  src/controllers/realtime/index.js
  test/controllers/realtime.test.js
Labels: changelog:enhancements

#330 Fix null id in arguments
  src/networkWrapper/protocols/http.js
  test/network/http.test.js
Labels: changelog:bug-fixes

#329 Remove realtime deprecated methods
  src/controllers/realtime/index.js
  test/controllers/realtime.test.js
Labels: changelog:enhancements

#332 realtime: fix bug
  src/controllers/realtime/index.js
  test/controllers/realtime.test.js
Labels: bug, changelog:breaking-changes, changelog:bug-fixes

#333 Kzl 791 fix exception when publish msg with rest api
  src/controllers/realtime/room.js
Labels: changelog:bug-fixes
