Repository kuzzleio/sdk-javascript, pull requests merged in 2018-07, with the labels that each got.

#295 fix http send
  src/networkWrapper/protocols/abstract/common.js
  src/networkWrapper/protocols/http.js
  test/network/http.test.js
  test/network/query.test.js
Labels: changelog:exclude

#294 Allow passing a custom network object to Kuzzle SDK constructor
  index.js
  src/Kuzzle.js
  src/networkWrapper/index.js
  src/networkWrapper/protocols/abstract/common.js
  src/networkWrapper/protocols/abstract/realtime.js
  src/networkWrapper/protocols/http.js
  src/networkWrapper/protocols/socketio.js
  src/networkWrapper/protocols/websocket.js
  test/kuzzle/connect.test.js
  test/kuzzle/constructor.test.js
  test/kuzzle/getters.test.js
  test/kuzzle/listenersManagement.test.js
  test/kuzzle/network.test.js
  test/kuzzle/query.test.js
  test/kuzzle/setters.test.js
  test/mocks/networkWrapper.mock.js
  test/network/http.test.js
  test/network/networkWrapper.test.js
  test/network/offlineQueue.test.js
  test/network/socketio.test.js
  test/network/websocket.test.js
Labels: changelog:enhancements

#297 update dependency
  package-lock.json
  package.json
Labels: changelog:exclude

#301 [6.x] collection.create can be used with a mapping
  package-lock.json
  package.json
  src/controllers/collection.js
  test/controllers/collection.test.js
Labels: changelog:enhancements

#300 [5.x] collection.create can be used with a mapping
  dist/kuzzle.js
  dist/kuzzle.js.map
  package-lock.json
  package.json
  src/Collection.js
  test/Collection/methods.test.js
  test/Room/methods.test.js
  test/SearchResult/constructor.test.js
  test/kuzzle/connect.test.js
  test/kuzzle/getStatistics.test.js
  test/kuzzle/login.test.js
  test/kuzzle/methods.test.js
  test/security/kuzzleSecurity/constructor.test.js
  test/security/kuzzleSecurity/credentialsMethods.test.js
  test/security/kuzzleSecurity/profilesMethods.test.js
  test/security/kuzzleSecurity/userMethods.test.js
  test/security/kuzzleUser/methods.test.js
  webpack.config.js
Labels: changelog:enhancements

#302 Release 5.0.12
  dist/kuzzle.js
  dist/kuzzle.js.map
  package-lock.json
  package.json
  src/Collection.js
  test/Collection/methods.test.js
  test/Room/methods.test.js
  test/SearchResult/constructor.test.js
  test/kuzzle/connect.test.js
  test/kuzzle/getStatistics.test.js
  test/kuzzle/login.test.js
  test/kuzzle/methods.test.js
  test/security/kuzzleSecurity/constructor.test.js
  test/security/kuzzleSecurity/credentialsMethods.test.js
  test/security/kuzzleSecurity/profilesMethods.test.js
  test/security/kuzzleSecurity/userMethods.test.js
  test/security/kuzzleUser/methods.test.js
  webpack.config.js
Labels: release
