Repository kuzzleio/sdk-javascript, pull requests merged in 2018-11, with the labels that each got.

#334 Fix bug in room notifications with multiple subscribes on same filter
  dist/kuzzle.js.map
  src/Room.js
  test/Room/methods.test.js
Labels: 5-dev, changelog:bug-fixes

#331 Change incoherent method returns
  src/controllers/auth.js
  src/controllers/index.js
  test/controllers/auth.test.js
  test/controllers/index.test.js
Labels: changelog:enhancements

#327 fix searchResult next
  package-lock.json
  src/controllers/searchResult/base.js
  test/controllers/searchResult/document.test.js
Labels: changelog:bug-fixes

#326 Harmonize SDK
  src/controllers/auth.js
  src/controllers/bulk.js
  src/controllers/collection.js
  test/controllers/auth.test.js
  test/controllers/bulk.test.js
  test/controllers/collection.test.js
Labels: 6-dev, changelog:enhancements

#337 'ms:sort' needs its options in the request's body
  package-lock.json
  src/controllers/memoryStorage.js
  test/controllers/memoryStorage.test.js
Labels: changelog:bug-fixes

#338 Fix undefined "volatile.sdkInstanceId" in sent queries
  src/Kuzzle.js
  src/networkWrapper/protocols/abstract/common.js
  test/network/http.test.js
  test/network/networkWrapper.test.js
  test/network/socketio.test.js
  test/network/websocket.test.js
Labels: changelog:bug-fixes
