Repository kuzzleio/sdk-javascript, pull requests merged in 2018-09, with the labels that each got.

#308 KZL 174 - Update README for SDK V6
  .travis.yml
  README.md
  deploy.sh
Labels: changelog:enhancements

#310 Release 5.0.13
  .gitignore
  dist/kuzzle.js.map
  package-lock.json
  package.json
  src/Document.js
  test/Document/methods.test.js
Labels: release

#311 Release 6.0.0-beta-1
  .travis.yml
  README.md
  deploy.sh
  package-lock.json
  package.json
Labels: release

#312 Rename deleteSpecification to deleteSpecifications
  src/controllers/collection.js
  test/controllers/collection.test.js
Labels: changelog:bug-fixes

#313 remove unused properties
  src/Kuzzle.js
  src/networkWrapper/protocols/abstract/common.js
  src/networkWrapper/protocols/abstract/realtime.js
  src/networkWrapper/protocols/http.js
Labels: changelog:enhancements

#315 fix jwt in query
  src/Kuzzle.js
Labels: changelog:bug-fixes

#316 Release 6.0.0-beta-2
  package-lock.json
  package.json
  src/Kuzzle.js
  src/controllers/collection.js
  src/networkWrapper/protocols/abstract/common.js
  src/networkWrapper/protocols/abstract/realtime.js
  src/networkWrapper/protocols/http.js
  test/controllers/collection.test.js
Labels: release

#317 document:delete to return the id of the deleted document
  src/controllers/document.js
  test/controllers/document.test.js
Labels: 6-dev, changelog:enhancements
