Repository kuzzleio/sdk-javascript, pull requests merged in 2019-05, with the labels that each got.

#391 Add isConnected
  features/steps/collection.js
  src/Kuzzle.js
  src/protocols/abstract/common.js
  src/protocols/http.js
Labels: changelog:enhancements, need-documentation

#394 Add default values for from/size to document:search
  src/controllers/document.js
  test/controllers/document.test.js
Labels: changelog:bug-fixes

#389 Remove usage of _meta
  features/steps/collection.js
  src/controllers/auth.js
  src/controllers/searchResult/user.js
  src/controllers/security/index.js
  src/controllers/security/profile.js
  src/controllers/security/role.js
  src/controllers/security/user.js
Labels: changelog:enhancements

#395 [KZL-1098] proxify kuzzle to avoid mistyping error
  .eslintrc.json
  src/Kuzzle.js
  src/proxify.js
  test/helpers/proxify.test.js
  test/kuzzle/proxy.test.js
Labels: changelog:enhancements

#398 Fix bulk return
  src/controllers/bulk.js
  test/controllers/bulk.test.js
Labels: changelog:bug-fixes

#390 Add authenticated property on Kuzzle object
  src/Kuzzle.js
  src/controllers/auth.js
  src/controllers/realtime/index.js
  src/core/Jwt.js
  test/controllers/auth.test.js
  test/controllers/realtime.test.js
  test/core/Jwt.test.js
  test/kuzzle/connect.test.js
  test/kuzzle/constructor.test.js
  test/kuzzle/getters.test.js
  test/kuzzle/protocol.test.js
  test/kuzzle/query.test.js
  test/kuzzle/setters.test.js
  test/mocks/generateJwt.mock.js
Labels: changelog:enhancements, need-documentation
