Repository kuzzleio/sdk-javascript, pull requests merged in 2019-11, with the labels that each got.

#456 Do not try to reconnect if the browser is offline
  package-lock.json
  package.json
  src/protocols/abstract/realtime.js
  test/mocks/window.mock.js
  test/protocol/socketio.test.js
  test/protocol/websocket.test.js
Labels: 6-dev, changelog:enhancements

#459 Release 6.2.6
  README.md
  package-lock.json
  package.json
  src/KuzzleError.js
  src/controllers/auth.js
  src/controllers/collection.js
  src/controllers/document.js
  src/controllers/index.js
  src/controllers/realtime/index.js
  src/controllers/security/index.js
  src/protocols/abstract/realtime.js
  test/controllers/auth.test.js
  test/controllers/collection.test.js
  test/controllers/document.test.js
  test/controllers/index.test.js
  test/controllers/realtime.test.js
  test/controllers/security.test.js
  test/mocks/window.mock.js
  test/protocol/socketio.test.js
  test/protocol/websocket.test.js
Labels: release

#455 Do not try to reconnect if the browser is offline
  codecov.yml
  package-lock.json
  package.json
  src/protocols/abstract/realtime.js
  test/mocks/window.mock.js
  test/protocol/socketio.test.js
  test/protocol/websocket.test.js
Labels: 7-dev, changelog:enhancements

#462 Fix erroneous error message on browser ws error
  src/protocols/websocket.js
  test/protocol/websocket.test.js
Labels: 6-dev, changelog:bug-fixes

#463 Fix erroneous error message on browser ws error
  src/protocols/websocket.js
  test/protocol/websocket.test.js
Labels: 7-dev, changelog:bug-fixes

#466 Release 6.2.7
  package-lock.json
  package.json
  src/protocols/websocket.js
  test/protocol/websocket.test.js
Labels: release

#464 Fix option refresh in queries
  .ci/doc/config.yml
  src/Kuzzle.js
  src/controllers/collection.js
  src/controllers/document.js
  src/controllers/index.js
  src/controllers/security/index.js
  test.js
  test.sh
  test/controllers/collection.test.js
  test/controllers/document.test.js
  test/controllers/security.test.js
  test1.js
Labels: changelog:bug-fixes

#467 Release 7.0.0
  .ci/doc/config.yml
  codecov.yml
  package-lock.json
  package.json
  src/Kuzzle.js
  src/controllers/collection.js
  src/controllers/document.js
  src/controllers/index.js
  src/controllers/security/index.js
  src/protocols/abstract/realtime.js
  src/protocols/websocket.js
  test.js
  test.sh
  test/controllers/collection.test.js
  test/controllers/document.test.js
  test/controllers/security.test.js
  test/mocks/window.mock.js
  test/protocol/socketio.test.js
  test/protocol/websocket.test.js
  test1.js
Labels: release

#470 Handle multi stable branches NPM.js deployments
  .travis.yml
Labels: 7-dev, changelog:exclude

#469 Handle deployments on stable branches
  .travis.yml
Labels: 6-dev, changelog:exclude

#471 Fix option refresh in queries
  src/Kuzzle.js
Labels: 6-dev, changelog:bug-fixes
