Repository kuzzleio/sdk-javascript, pull requests merged in 2019-08, with the labels that each got.

#433 Merge new documentation framework
  .travis.yml
  doc/doc.sh
  package.json
Labels: do not merge

#435 Reactivate documentation deployment
  .travis.yml
Labels: changelog:exclude, do not merge

#432 Fix mUpdate documentation
  doc/6/controllers/document/m-update/snippets/m-update.js
Labels: changelog:exclude

#441 Fix base64 decoding for the JWT in React Native
  features/support/hooks.js
  package-lock.json
  package.json
  src/core/Jwt.js
  test/core/Jwt.test.js
Labels: changelog:bug-fixes

#437 Fix duplicate subscriptions on reconnect
  .eslintrc.json
  features/support/hooks.js
  publish.js
  src/Kuzzle.js
  src/controllers/realtime/index.js
  src/controllers/realtime/room.js
  test/controllers/auth.test.js
  test/controllers/realtime.test.js
  test/controllers/realtime/room.test.js
  test/kuzzle/connect.test.js
  test/kuzzle/getters.test.js
  test/kuzzle/setters.test.js
Labels: changelog:bug-fixes

#440 Fix query documentation
  .gitignore
  doc/5/core-classes/kuzzle/query/index.md
Labels: changelog:exclude
