Repository kuzzleio/sdk-javascript, pull requests merged in 2019-12, with the labels that each got.

#475 Release 6.2.8
  package-lock.json
  package.json
  src/Kuzzle.js
Labels: release

#473 Fix search with size=0
  src/controllers/document.js
  test/controllers/document.test.js
Labels: 7-dev, changelog:bug-fixes

#474 Fix search with size=0
  src/controllers/document.js
  test/controllers/document.test.js
Labels: 6-dev, changelog:bug-fixes

#477 [ci] Separate latest from stable deploy
  .ci/test-docs.sh
  .travis.yml
  doc/7/controllers/security/create-or-replace-profile/snippets/create-or-replace-profile.js
  doc/7/controllers/security/create-or-replace-profile/snippets/create-or-replace-profile.test.yml
  doc/7/controllers/security/create-profile/snippets/create-profile.js
  doc/7/controllers/security/get-profile-rights/snippets/get-profile-rights.test.yml
  doc/7/controllers/security/get-profile/snippets/get-profile.test.yml
  doc/7/controllers/security/update-profile/snippets/update-profile.js
Labels: changelog:exclude
