Repository kuzzleio/sdk-javascript, pull requests merged in 2019-07, with the labels that each got.

#405 Add-getting-started-vuejs-without-vuex
  doc/6/getting-started/vuejs/.gitignore
  doc/6/getting-started/vuejs/cypress.json
  doc/6/getting-started/vuejs/cypress/fixtures/Environment.1.json
  doc/6/getting-started/vuejs/cypress/fixtures/Environment.2.json
  doc/6/getting-started/vuejs/cypress/fixtures/Environment.3.json
  doc/6/getting-started/vuejs/cypress/fixtures/Environment.4.json
  doc/6/getting-started/vuejs/cypress/integration/chat.spec.js
  doc/6/getting-started/vuejs/cypress/plugins/index.js
  doc/6/getting-started/vuejs/cypress/support/commands.js
  doc/6/getting-started/vuejs/cypress/support/index.js
  doc/6/getting-started/vuejs/package.json
  doc/6/getting-started/vuejs/without-vuex/babel.config.js
  doc/6/getting-started/vuejs/without-vuex/public/favicon.ico
  doc/6/getting-started/vuejs/without-vuex/public/index.html
  doc/6/getting-started/vuejs/without-vuex/src/App.vue
  doc/6/getting-started/vuejs/without-vuex/src/assets/logo.png
  doc/6/getting-started/vuejs/without-vuex/src/main.js
  doc/6/getting-started/vuejs/without-vuex/src/services/kuzzle.js
Labels: 6-dev

#408 Make createUser id parameter optional
  src/controllers/security/index.js
  test/controllers/security.test.js
Labels: changelog:enhancements

#413 fix-vuejs-getting-started-tests
  .travis.yml
  doc/6/getting-started/vuejs/.gitignore
  doc/6/getting-started/vuejs/cypress.json
  doc/6/getting-started/vuejs/cypress/fixtures/Elrond.json
  doc/6/getting-started/vuejs/cypress/fixtures/Legolas.json
  doc/6/getting-started/vuejs/cypress/fixtures/Sam.json
  doc/6/getting-started/vuejs/cypress/fixtures/Sauron.json
  doc/6/getting-started/vuejs/cypress/integration/chat.spec.js
  doc/6/getting-started/vuejs/cypress/support/commands.js
  doc/6/getting-started/vuejs/package-lock.json
  doc/6/getting-started/vuejs/package.json
  doc/6/getting-started/vuejs/without-vuex/src/App.vue
  package-lock.json
  package.json
  test-docs.sh
Labels: changelog:bug-fixes, do not merge

#416 Remove-vuejs-getting-started
  doc/6/getting-started/vuejs/.gitignore
  doc/6/getting-started/vuejs/cypress.json
  doc/6/getting-started/vuejs/cypress/fixtures/Elrond.json
  doc/6/getting-started/vuejs/cypress/fixtures/Legolas.json
  doc/6/getting-started/vuejs/cypress/fixtures/Sam.json
  doc/6/getting-started/vuejs/cypress/fixtures/Sauron.json
  doc/6/getting-started/vuejs/cypress/integration/chat.spec.js
  doc/6/getting-started/vuejs/cypress/plugins/index.js
  doc/6/getting-started/vuejs/cypress/support/commands.js
  doc/6/getting-started/vuejs/cypress/support/index.js
  doc/6/getting-started/vuejs/index.md
  doc/6/getting-started/vuejs/package-lock.json
  doc/6/getting-started/vuejs/package.json
  doc/6/getting-started/vuejs/without-vuex/babel.config.js
  doc/6/getting-started/vuejs/without-vuex/index.md
  doc/6/getting-started/vuejs/without-vuex/public/favicon.ico
  doc/6/getting-started/vuejs/without-vuex/public/index.html
  doc/6/getting-started/vuejs/without-vuex/src/App.vue
  doc/6/getting-started/vuejs/without-vuex/src/assets/logo.png
  doc/6/getting-started/vuejs/without-vuex/src/main.js
  doc/6/getting-started/vuejs/without-vuex/src/services/kuzzle.js
  test-docs.sh
Labels: changelog:bug-fixes

#415 Add Travis Nightly
  .travis.yml
Labels: changelog:exclude

#420 Fix http protocol unresolved promise on connection error
  src/protocols/http.js
  test/protocol/http.test.js
Labels: changelog:bug-fixes

#419 Add bulk:write and bulk:mWrite
  doc/6/controllers/bulk/mWrite/index.md
  doc/6/controllers/bulk/mWrite/snippets/mWrite.js
  doc/6/controllers/bulk/mWrite/snippets/mWrite.test.yml
  doc/6/controllers/bulk/write/index.md
  doc/6/controllers/bulk/write/snippets/write.js
  doc/6/controllers/bulk/write/snippets/write.test.yml
  src/controllers/bulk.js
  test/controllers/bulk.test.js
Labels: changelog:new-features

#422 Fix bug when decoding JWT in browser
  src/core/Jwt.js
  test/core/Jwt.test.js
Labels: changelog:bug-fixes

#424 Prevent pending request leak when disconnect the SDK
  doc/6/core-classes/kuzzle/disconnect/index.md
  src/protocols/abstract/common.js
  test/protocol/common.test.js
Labels: changelog:bug-fixes

#423 Emit queryError event on malformed request
  doc/6/essentials/events/index.md
  src/protocols/websocket.js
  test/protocol/websocket.test.js
Labels: changelog:enhancements

#430 [CI] Fix documentation deployment conditions
  .travis.yml
Labels: changelog:exclude

#428 Properly handle boolean flags in HTTP querystrings
  src/protocols/http.js
  test/protocol/http.test.js
Labels: changelog:bug-fixes
