Repository kuzzleio/sdk-javascript, pull requests merged in 2019-10, with the labels that each got.

#444 fix 404
  doc/5/core-classes/kuzzle/query/index.md
Labels: changelog:exclude

#448 Rewrite the SearchResult core class documentation
  doc/6/core-classes/search-result/introduction/index.md
  doc/6/core-classes/search-result/next/index.md
  doc/6/core-classes/search-result/next/snippets/fromsize.js
  doc/6/core-classes/search-result/next/snippets/fromsize.test.yml
  doc/6/core-classes/search-result/next/snippets/scroll.js
  doc/6/core-classes/search-result/next/snippets/scroll.test.yml
  doc/6/core-classes/search-result/properties/index.md
Labels: 6-dev, changelog:exclude

#449 Rewrite the SearchResult core class documentation
  doc/7/core-classes/search-result/introduction/index.md
  doc/7/core-classes/search-result/next/index.md
  doc/7/core-classes/search-result/next/snippets/fromsize.js
  doc/7/core-classes/search-result/next/snippets/fromsize.test.yml
  doc/7/core-classes/search-result/next/snippets/scroll.js
  doc/7/core-classes/search-result/next/snippets/scroll.test.yml
  doc/7/core-classes/search-result/properties/index.md
Labels: 7-dev, changelog:exclude

#453 Fix connected property
  src/protocols/abstract/common.js
  test/protocol/common.test.js
Labels: 7-dev, changelog:bug-fixes

#452 Fix connected property value
  package-lock.json
  package.json
  src/protocols/abstract/common.js
  test/protocol/common.test.js
Labels: 6-dev, changelog:bug-fixes

#451 Remove local checks for arguments
  src/KuzzleError.js
  src/controllers/auth.js
  src/controllers/collection.js
  src/controllers/document.js
  src/controllers/index.js
  src/controllers/realtime/index.js
  src/controllers/security/index.js
  test/controllers/auth.test.js
  test/controllers/collection.test.js
  test/controllers/document.test.js
  test/controllers/index.test.js
  test/controllers/realtime.test.js
  test/controllers/security.test.js
Labels: 6-dev, changelog:enhancements

#431 Add getting started Vue.js
  .gitignore
  doc/6/getting-started/.vuejs/cypress.json
  doc/6/getting-started/.vuejs/cypress/fixtures/Elrond.json
  doc/6/getting-started/.vuejs/cypress/fixtures/Legolas.json
  doc/6/getting-started/.vuejs/cypress/fixtures/Sam.json
  doc/6/getting-started/.vuejs/cypress/fixtures/Sauron.json
  doc/6/getting-started/.vuejs/cypress/integration/chat.spec.js
  doc/6/getting-started/.vuejs/cypress/plugins/index.js
  doc/6/getting-started/.vuejs/cypress/support/commands.js
  doc/6/getting-started/.vuejs/cypress/support/index.js
  doc/6/getting-started/.vuejs/package-lock.json
  doc/6/getting-started/.vuejs/package.json
  doc/6/getting-started/.vuejs/standalone/babel.config.js
  doc/6/getting-started/.vuejs/standalone/public/favicon.ico
  doc/6/getting-started/.vuejs/standalone/public/index.html
  doc/6/getting-started/.vuejs/standalone/src/App.vue
  doc/6/getting-started/.vuejs/standalone/src/assets/logo.png
  doc/6/getting-started/.vuejs/standalone/src/main.js
  doc/6/getting-started/.vuejs/standalone/src/services/kuzzle.js
  doc/6/getting-started/vuejs/index.md
  doc/6/getting-started/vuejs/standalone/index.md
  doc/6/getting-started/vuejs/standalone/snippets/App.vue.snippet
  doc/6/getting-started/vuejs/standalone/snippets/kuzzle.js.snippet
  test-docs.sh
Labels: 6-dev, changelog:exclude

#436 Add getting started React
  .gitignore
  doc/6/getting-started/.react/.eslintrc.json
  doc/6/getting-started/.react/.gitignore
  doc/6/getting-started/.react/cypress.json
  doc/6/getting-started/.react/cypress/fixtures/Legolas.json
  doc/6/getting-started/.react/cypress/fixtures/Sam.json
  doc/6/getting-started/.react/cypress/fixtures/Sauron.json
  doc/6/getting-started/.react/cypress/integration/chat.spec.js
  doc/6/getting-started/.react/cypress/plugins/index.js
  doc/6/getting-started/.react/cypress/support/commands.js
  doc/6/getting-started/.react/cypress/support/index.js
  doc/6/getting-started/.react/package.json
  doc/6/getting-started/.react/public/favicon.ico
  doc/6/getting-started/.react/public/index.html
  doc/6/getting-started/.react/public/manifest.json
  doc/6/getting-started/.react/src/App.css
  doc/6/getting-started/.react/src/App.js
  doc/6/getting-started/.react/src/App.test.js
  doc/6/getting-started/.react/src/index.css
  doc/6/getting-started/.react/src/index.js
  doc/6/getting-started/.react/src/logo.svg
  doc/6/getting-started/.react/src/serviceWorker.js
  doc/6/getting-started/.react/src/services/kuzzle.js
  doc/6/getting-started/.react/src/state/actions.js
  doc/6/getting-started/.react/src/state/reducers.js
  doc/6/getting-started/.react/src/state/sagas.js
  doc/6/getting-started/.react/yarn.lock
  doc/6/getting-started/react/index.md
  doc/6/getting-started/react/with-redux/index.md
  doc/6/getting-started/react/with-redux/snippets/App.js.snippet
  doc/6/getting-started/react/with-redux/snippets/actions.js.snippet
  doc/6/getting-started/react/with-redux/snippets/index.js.snippet
  doc/6/getting-started/react/with-redux/snippets/kuzzle.js.snippet
  doc/6/getting-started/react/with-redux/snippets/reducers.js.snippet
  doc/6/getting-started/react/with-redux/snippets/sagas.js.snippet
  test-docs.sh
Labels: 6-dev, changelog:exclude

#454 Import Vue.js and React getting started from v6
  .gitignore
  doc/7/getting-started/.react/.eslintrc.json
  doc/7/getting-started/.react/.gitignore
  doc/7/getting-started/.react/cypress.json
  doc/7/getting-started/.react/cypress/fixtures/Legolas.json
  doc/7/getting-started/.react/cypress/fixtures/Sam.json
  doc/7/getting-started/.react/cypress/fixtures/Sauron.json
  doc/7/getting-started/.react/cypress/integration/chat.spec.js
  doc/7/getting-started/.react/cypress/plugins/index.js
  doc/7/getting-started/.react/cypress/support/commands.js
  doc/7/getting-started/.react/cypress/support/index.js
  doc/7/getting-started/.react/package.json
  doc/7/getting-started/.react/public/favicon.ico
  doc/7/getting-started/.react/public/index.html
  doc/7/getting-started/.react/public/manifest.json
  doc/7/getting-started/.react/src/App.css
  doc/7/getting-started/.react/src/App.js
  doc/7/getting-started/.react/src/App.test.js
  doc/7/getting-started/.react/src/index.css
  doc/7/getting-started/.react/src/index.js
  doc/7/getting-started/.react/src/logo.svg
  doc/7/getting-started/.react/src/serviceWorker.js
  doc/7/getting-started/.react/src/services/kuzzle.js
  doc/7/getting-started/.react/src/state/actions.js
  doc/7/getting-started/.react/src/state/reducers.js
  doc/7/getting-started/.react/src/state/sagas.js
  doc/7/getting-started/.react/yarn.lock
  doc/7/getting-started/.vuejs/cypress.json
  doc/7/getting-started/.vuejs/cypress/fixtures/Elrond.json
  doc/7/getting-started/.vuejs/cypress/fixtures/Legolas.json
  doc/7/getting-started/.vuejs/cypress/fixtures/Sam.json
  doc/7/getting-started/.vuejs/cypress/fixtures/Sauron.json
  doc/7/getting-started/.vuejs/cypress/integration/chat.spec.js
  doc/7/getting-started/.vuejs/cypress/plugins/index.js
  doc/7/getting-started/.vuejs/cypress/support/commands.js
  doc/7/getting-started/.vuejs/cypress/support/index.js
  doc/7/getting-started/.vuejs/package-lock.json
  doc/7/getting-started/.vuejs/package.json
  doc/7/getting-started/.vuejs/standalone/babel.config.js
  doc/7/getting-started/.vuejs/standalone/public/favicon.ico
  doc/7/getting-started/.vuejs/standalone/public/index.html
  doc/7/getting-started/.vuejs/standalone/src/App.vue
  doc/7/getting-started/.vuejs/standalone/src/assets/logo.png
  doc/7/getting-started/.vuejs/standalone/src/main.js
  doc/7/getting-started/.vuejs/standalone/src/services/kuzzle.js
  doc/7/getting-started/react/index.md
  doc/7/getting-started/react/with-redux/index.md
  doc/7/getting-started/react/with-redux/snippets/App.js.snippet
  doc/7/getting-started/react/with-redux/snippets/actions.js.snippet
  doc/7/getting-started/react/with-redux/snippets/index.js.snippet
  doc/7/getting-started/react/with-redux/snippets/kuzzle.js.snippet
  doc/7/getting-started/react/with-redux/snippets/reducers.js.snippet
  doc/7/getting-started/react/with-redux/snippets/sagas.js.snippet
  doc/7/getting-started/vuejs/index.md
  doc/7/getting-started/vuejs/standalone/index.md
  doc/7/getting-started/vuejs/standalone/snippets/App.vue.snippet
  doc/7/getting-started/vuejs/standalone/snippets/kuzzle.js.snippet
  test-docs.sh
Labels: 7-dev, changelog:exclude

#450 Remove local checks for arguments
  .ci/docker-compose.yml
  .ci/test-docs.sh
  doc/7/getting-started/.react/cypress/support/commands.js
  doc/7/getting-started/.vuejs/cypress/support/commands.js
  features/steps/document.js
  features/support/hooks.js
  package.json
  src/Kuzzle.js
  src/KuzzleError.js
  src/controllers/auth.js
  src/controllers/collection.js
  src/controllers/document.js
  src/controllers/index.js
  src/controllers/realtime/index.js
  src/controllers/security/index.js
  test/controllers/auth.test.js
  test/controllers/collection.test.js
  test/controllers/document.test.js
  test/controllers/index.test.js
  test/controllers/realtime.test.js
  test/controllers/security.test.js
  test/kuzzle/query.test.js
Labels: 7-dev, changelog:enhancements
