Repository kuzzleio/sdk-javascript, pull requests merged in 2019-04, with the labels that each got.

#384 [fix] search API: "sort" and "search_after" must be in the requests body
  src/controllers/searchResult/base.js
  test/controllers/searchResult/document.test.js
  test/controllers/searchResult/profile.test.js
  test/controllers/searchResult/specifications.test.js
  test/controllers/searchResult/user.test.js
Labels: changelog:bug-fixes

#385 Add Realtime.createRestrictedUser method
  src/controllers/security/index.js
  test/controllers/security.test.js
Labels: changelog:enhancements

#388 Use BaseController class for controllers
  src/Kuzzle.js
  src/controllers/auth.js
  src/controllers/base.js
  src/controllers/bulk.js
  src/controllers/collection.js
  src/controllers/document.js
  src/controllers/index.js
  src/controllers/memoryStorage.js
  src/controllers/realtime/index.js
  src/controllers/security/index.js
  src/controllers/server.js
  test/controllers/server.test.js
  test/kuzzle/useController.test.js
Labels: changelog:new-features

#393 Release 6.1.1
  package-lock.json
  package.json
  src/Kuzzle.js
  src/controllers/auth.js
  src/controllers/base.js
  src/controllers/bulk.js
  src/controllers/collection.js
  src/controllers/document.js
  src/controllers/index.js
  src/controllers/memoryStorage.js
  src/controllers/realtime/index.js
  src/controllers/searchResult/base.js
  src/controllers/searchResult/profile.js
  src/controllers/searchResult/role.js
  src/controllers/searchResult/user.js
  src/controllers/security/index.js
  src/controllers/server.js
  test/controllers/searchResult/document.test.js
  test/controllers/searchResult/profile.test.js
  test/controllers/searchResult/role.test.js
  test/controllers/searchResult/specifications.test.js
  test/controllers/searchResult/user.test.js
  test/controllers/security.test.js
  test/controllers/server.test.js
  test/kuzzle/useController.test.js
Labels: release
