Repository kuzzleio/sdk-javascript, pull requests merged in 2019-01, with the labels that each got.

#353 Add method to use custom controllers in the SDK
  index.js
  src/Kuzzle.js
  src/controllers/base.js
  src/protocols/http.js
  test/kuzzle/useController.test.js
Labels: changelog:new-features, need-documentation

#355 React native compatibility
  .babelrc.js
  README.md
  build.js
  package-lock.json
  package.json
  src/controllers/auth.js
  src/controllers/base.js
  src/controllers/bulk.js
  src/controllers/collection.js
  src/controllers/document.js
  src/controllers/index.js
  src/controllers/memoryStorage.js
  src/controllers/realtime/index.js
  src/controllers/security/index.js
  src/controllers/server.js
  src/protocols/websocket.js
  webpack.config.js
Labels: changelog:bug-fixes

#363 Release 6.0.0-beta-6
  .babelrc.js
  README.md
  build.js
  package-lock.json
  package.json
  src/Kuzzle.js
  src/controllers/auth.js
  src/controllers/base.js
  src/controllers/bulk.js
  src/controllers/collection.js
  src/controllers/document.js
  src/controllers/index.js
  src/controllers/memoryStorage.js
  src/controllers/realtime/index.js
  src/controllers/security/index.js
  src/controllers/server.js
  src/protocols/websocket.js
  test/kuzzle/connect.test.js
  webpack.config.js
Labels: release
