Repository kuzzleio/sdk-javascript, pull requests merged in 2020-04, with the labels that each got.

#505 Lighter production dependencies
  .gitignore
  .npmignore
  CHANGELOG.md
  build.js
  package-lock.json
  package.json
Labels: 7-dev, changelog:enhancements

#502 Remove pagination from collection list
  doc/7/controllers/collection/list/index.md
  src/controllers/Collection.js
  test/controllers/collection.test.js
Labels: 7-dev, changelog:enhancements

#504 add getting started for reactJS
  .ci/test-docs.sh
  doc/7/getting-started/.react/standalone/.gitignore
  doc/7/getting-started/.react/standalone/cypress.json
  doc/7/getting-started/.react/standalone/cypress/fixtures/Elrond.json
  doc/7/getting-started/.react/standalone/cypress/fixtures/Legolas.json
  doc/7/getting-started/.react/standalone/cypress/fixtures/Sam.json
  doc/7/getting-started/.react/standalone/cypress/fixtures/Sauron.json
  doc/7/getting-started/.react/standalone/cypress/integration/react-chat.spec.js
  doc/7/getting-started/.react/standalone/cypress/plugins/index.js
  doc/7/getting-started/.react/standalone/cypress/support/commands.js
  doc/7/getting-started/.react/standalone/cypress/support/index.js
  doc/7/getting-started/.react/standalone/package-lock.json
  doc/7/getting-started/.react/standalone/package.json
  doc/7/getting-started/.react/standalone/public/favicon.ico
  doc/7/getting-started/.react/standalone/public/index.html
  doc/7/getting-started/.react/standalone/public/manifest.json
  doc/7/getting-started/.react/standalone/public/robots.txt
  doc/7/getting-started/.react/standalone/src/App.css
  doc/7/getting-started/.react/standalone/src/App.js
  doc/7/getting-started/.react/standalone/src/index.js
  doc/7/getting-started/.react/standalone/src/services/kuzzle.js
  doc/7/getting-started/.react/with-redux/.eslintrc.json
  doc/7/getting-started/.react/with-redux/.gitignore
  doc/7/getting-started/.react/with-redux/cypress.json
  doc/7/getting-started/.react/with-redux/cypress/fixtures/Legolas.json
  doc/7/getting-started/.react/with-redux/cypress/fixtures/Sam.json
  doc/7/getting-started/.react/with-redux/cypress/fixtures/Sauron.json
  doc/7/getting-started/.react/with-redux/cypress/integration/react-chat.spec.js
  doc/7/getting-started/.react/with-redux/cypress/plugins/index.js
  doc/7/getting-started/.react/with-redux/cypress/support/commands.js
  doc/7/getting-started/.react/with-redux/cypress/support/index.js
  doc/7/getting-started/.react/with-redux/package-lock.json
  doc/7/getting-started/.react/with-redux/package.json
  doc/7/getting-started/.react/with-redux/public/favicon.ico
  doc/7/getting-started/.react/with-redux/public/index.html
  doc/7/getting-started/.react/with-redux/public/manifest.json
  doc/7/getting-started/.react/with-redux/src/App.css
  doc/7/getting-started/.react/with-redux/src/App.js
  doc/7/getting-started/.react/with-redux/src/App.test.js
  doc/7/getting-started/.react/with-redux/src/index.css
  doc/7/getting-started/.react/with-redux/src/index.js
  doc/7/getting-started/.react/with-redux/src/logo.svg
  doc/7/getting-started/.react/with-redux/src/serviceWorker.js
  doc/7/getting-started/.react/with-redux/src/services/kuzzle.js
  doc/7/getting-started/.react/with-redux/src/state/actions.js
  doc/7/getting-started/.react/with-redux/src/state/reducers.js
  doc/7/getting-started/.react/with-redux/src/state/sagas.js
  doc/7/getting-started/.react/with-redux/yarn.lock
  doc/7/getting-started/react/standalone/index.md
  doc/7/getting-started/react/standalone/snippets/App.css.snippet
  doc/7/getting-started/react/standalone/snippets/App.js.snippet
  doc/7/getting-started/react/standalone/snippets/kuzzle.js.snippet
  doc/7/getting-started/react/with-redux/snippets/App.js.snippet
  doc/7/getting-started/react/with-redux/snippets/actions.js.snippet
  doc/7/getting-started/react/with-redux/snippets/index.js.snippet
  doc/7/getting-started/react/with-redux/snippets/kuzzle.js.snippet
  doc/7/getting-started/react/with-redux/snippets/reducers.js.snippet
  doc/7/getting-started/react/with-redux/snippets/sagas.js.snippet
Labels: changelog:enhancements

#507 Fix collection getMapping
  .gitignore
  doc/7/getting-started/react-native/index.md
  src/controllers/Collection.js
  test-js.js
  test-sdk.js
  test/controllers/collection.test.js
Labels: 7-dev, changelog:bug-fixes

#509 Add the rate limit property to Profile objects
  src/controllers/Security.js
  src/core/searchResult/Profile.js
  src/core/security/Profile.js
  test/controllers/security.test.js
  test/core/security/profile.test.js
Labels: 7-dev, changelog:enhancements

#510 Add security:refresh
  doc/7/controllers/security/refresh/index.md
  doc/7/controllers/security/refresh/snippets/refresh.js
  doc/7/controllers/security/refresh/snippets/refresh.test.yml
  src/controllers/Security.js
  test/controllers/security.test.js
Labels: changelog:new-features

#511 Avoid to mutate user options
  src/controllers/Collection.js
  src/controllers/Document.js
  src/controllers/Security.js
  src/controllers/Server.js
  test/controllers/collection.test.js
  test/controllers/document.test.js
  test/controllers/security.test.js
  test/controllers/server.test.js
Labels: 7-dev, changelog:bug-fixes

#512 Fix token expired
  src/Kuzzle.js
  src/controllers/Auth.js
  src/controllers/Realtime.js
  src/protocols/abstract/Base.js
  test/controllers/auth.test.js
  test/controllers/realtime.test.js
  test/protocol/Base.test.js
Labels: 7-dev, changelog:bug-fixes

#508 Fix SearchResult.next with sort/size
  doc/7/core-classes/search-result/next/index.md
  doc/7/core-classes/search-result/next/snippets/sortsize.js
  doc/7/core-classes/search-result/next/snippets/sortsize.test.yml
  src/core/searchResult/Role.js
  src/core/searchResult/SearchResultBase.js
  test/core/searchResult/document.test.js
  test/core/searchResult/profile.test.js
  test/core/searchResult/role.test.js
  test/core/searchResult/specifications.test.js
  test/core/searchResult/user.test.js
Labels: 7-dev, changelog:bug-fixes

#513 Release 7.2.0
  .gitignore
  doc/7/controllers/security/refresh/index.md
  doc/7/controllers/security/refresh/snippets/refresh.js
  doc/7/controllers/security/refresh/snippets/refresh.test.yml
  doc/7/core-classes/search-result/next/index.md
  doc/7/core-classes/search-result/next/snippets/sortsize.js
  doc/7/core-classes/search-result/next/snippets/sortsize.test.yml
  doc/7/getting-started/react-native/index.md
  package-lock.json
  package.json
  src/Kuzzle.js
  src/controllers/Auth.js
  src/controllers/Collection.js
  src/controllers/Document.js
  src/controllers/Realtime.js
  src/controllers/Security.js
  src/controllers/Server.js
  src/core/searchResult/Profile.js
  src/core/searchResult/Role.js
  src/core/searchResult/SearchResultBase.js
  src/core/security/Profile.js
  src/protocols/abstract/Base.js
  test-js.js
  test-sdk.js
  test/controllers/auth.test.js
  test/controllers/collection.test.js
  test/controllers/document.test.js
  test/controllers/realtime.test.js
  test/controllers/security.test.js
  test/controllers/server.test.js
  test/core/searchResult/document.test.js
  test/core/searchResult/profile.test.js
  test/core/searchResult/role.test.js
  test/core/searchResult/specifications.test.js
  test/core/searchResult/user.test.js
  test/core/security/profile.test.js
  test/protocol/Base.test.js
Labels: release
