Repository kuzzleio/sdk-javascript, pull requests merged in 2020-11, with the labels that each got.

#554 Fix typo mget doc
  doc/7/controllers/document/m-get/index.md
Labels: 7-dev, changelog:exclude

#556 Export more interfaces for Typescript
  index.ts
  package-lock.json
  package.json
  src/controllers/Realtime.ts
  src/utils/interfaces.ts
Labels: 7-dev, changelog:enhancements

#558 Release 7.4.2
  index.ts
  package-lock.json
  package.json
  src/controllers/Realtime.ts
  src/utils/interfaces.ts
Labels: release

#559 Remove stacktrace enhancement
  .travis.yml
  package-lock.json
  package.json
  src/KuzzleError.ts
Labels: 7-dev, changelog:bug-fixes
