Repository kuzzleio/sdk-javascript, pull requests merged in 2020-07, with the labels that each got.

#527 Add typescript support for Document controller
  .eslintignore
  .gitignore
  doc/7/controllers/document/validate/index.md
  src/Kuzzle.ts
  src/controllers/Auth.ts
  src/controllers/Document.js
  src/controllers/Document.ts
  src/core/searchResult/Document.ts
  src/core/searchResult/SearchResultBase.ts
  src/utils/interfaces.ts
  tsconfig.json
Labels: 7-dev, changelog:new-features

#532 Encode URI parameters when using the HTTTP protocol
  features/steps/document.js
  index.ts
  package.json
  src/controllers/Document.ts
  src/core/searchResult/Document.ts
  src/protocols/Http.js
  test/controllers/document.test.js
  test/core/searchResult/document.test.js
  test/protocol/Http.test.js
Labels: 7-dev, changelog:bug-fixes

#523 Add support for the collection:delete API action
  doc/7/controllers/collection/delete/index.md
  doc/7/controllers/collection/delete/snippets/delete-specifications.js
  doc/7/controllers/collection/delete/snippets/delete-specifications.test.yml
  src/controllers/Collection.js
  src/controllers/Index.js
  test/controllers/collection.test.js
Labels: 7-dev, changelog:enhancements
