Repository kuzzleio/sdk-javascript, pull requests merged in 2020-10, with the labels that each got.

#546 Remove "scroll" option from security:searchRoles doc
  doc/7/controllers/security/search-roles/index.md
Labels: 7-dev, changelog:exclude

#550 Fix collection:list documentation
  doc/7/controllers/collection/list/index.md
  doc/7/controllers/collection/update/index.md
  doc/7/controllers/security/search-api-keys/index.md
  doc/7/controllers/security/search-api-keys/snippets/search-api-keys.test.yml
  doc/7/getting-started/.react-native/package.json
  doc/7/getting-started/.react/with-redux/package.json
  doc/7/getting-started/.vuejs/package.json
  src/controllers/Security.js
Labels: changelog:exclude

#551 Export interfaces
  index.ts
Labels: 7-dev, changelog:enhancements

#552 Upgrade to typescript 4 compatible code
  .ci/doc/eslint.json
  .ci/doc/templates/default.tpl.js
  .ci/test-docs.sh
  .eslintrc-ts.json
  doc/7/controllers/auth/delete-api-key/snippets/delete-api-key.js
  doc/7/controllers/auth/delete-api-key/snippets/delete-api-key.test.yml
  package-lock.json
  package.json
  src/protocols/WebSocket.ts
  src/protocols/abstract/Base.ts
  webpack.config.js
Labels: 7-dev, changelog:enhancements

#553 Release 7.4.1
  .ci/doc/eslint.json
  .ci/doc/templates/default.tpl.js
  .ci/test-docs.sh
  .eslintrc-ts.json
  doc/7/controllers/auth/delete-api-key/snippets/delete-api-key.js
  doc/7/controllers/auth/delete-api-key/snippets/delete-api-key.test.yml
  doc/7/getting-started/react-native/index.md
  doc/7/index.md
  index.ts
  package-lock.json
  package.json
  src/controllers/Realtime.ts
  src/protocols/WebSocket.ts
  src/protocols/abstract/Base.ts
  test/controllers/realtime.test.js
  webpack.config.js
Labels: release
