Repository kuzzleio/sdk-javascript, pull requests merged in 2020-03, with the labels that each got.

#494 Add information about scroll
  doc/7/controllers/document/search/index.md
  doc/7/core-classes/kuzzle-error/introduction/index.md
  doc/7/core-classes/search-result/next/index.md
  doc/7/essentials/error-handling/index.md
Labels: 7-dev, changelog:exclude

#497 Fix erroneous requests due to HTTP-specific settings
  .mocharc.json
  doc/7/core-classes/kuzzle-error/introduction/index.md
  doc/7/essentials/error-handling/index.md
  package-lock.json
  package.json
  src/Kuzzle.js
  src/controllers/document.js
  src/controllers/security/index.js
  src/protocols/http.js
  test/controllers/document.test.js
  test/mocha.opts
  test/protocol/http.test.js
Labels: changelog:bug-fixes

#496 Allow better extensibility
  index.js
  src/controllers/document.js
  src/controllers/searchResult/index.js
Labels: 7-dev, changelog:exclude

#498 Hotfix document search http
  package-lock.json
  package.json
  src/controllers/document.js
  src/protocols/http.js
  test/controllers/document.test.js
  test/protocol/http.test.js
Labels: 7-dev, changelog:bug-fixes

#499 Release 7.1.2
  doc/7/controllers/document/search/index.md
  doc/7/core-classes/search-result/next/index.md
  index.js
  package-lock.json
  package.json
  src/controllers/document.js
  src/controllers/searchResult/index.js
  src/protocols/http.js
  test/controllers/document.test.js
  test/protocol/http.test.js
Labels: release

#500 Allow to use custom controller in another package
  doc/7/controllers/collection/search-specifications/snippets/search-specifications.js
  doc/7/core-classes/search-result/next/snippets/scroll.js
  package-lock.json
  package.json
  src/Kuzzle.js
  test/controllers/document.test.js
  test/controllers/searchResult/document.test.js
  test/controllers/searchResult/profile.test.js
  test/controllers/searchResult/role.test.js
  test/controllers/searchResult/specifications.test.js
  test/controllers/searchResult/user.test.js
  test/controllers/security.test.js
  test/kuzzle/useController.test.js
Labels: 7-dev, changelog:bug-fixes
