Repository kuzzleio/sdk-javascript, pull requests merged in 2020-01, with the labels that each got.

#476 Add a "force" option to create/update role
  .travis.yml
  doc/7/controllers/security/create-or-replace-role/index.md
  doc/7/controllers/security/create-role/index.md
  doc/7/controllers/security/update-role/index.md
  src/controllers/security/index.js
  test/controllers/security.test.js
Labels: changelog:enhancements

#478 Add API key methods
  .ci/doc/docker-compose.yml
  .ci/docker-compose.yml
  doc/7/controllers/auth/create-api-key/index.md
  doc/7/controllers/auth/create-api-key/snippets/create-api-key.js
  doc/7/controllers/auth/create-api-key/snippets/create-api-key.test.yml
  doc/7/controllers/auth/delete-api-key/index.md
  doc/7/controllers/auth/delete-api-key/snippets/delete-api-key.js
  doc/7/controllers/auth/delete-api-key/snippets/delete-api-key.test.yml
  doc/7/controllers/auth/search-api-keys/index.md
  doc/7/controllers/auth/search-api-keys/snippets/search-api-keys.js
  doc/7/controllers/auth/search-api-keys/snippets/search-api-keys.test.yml
  doc/7/controllers/security/create-api-key/index.md
  doc/7/controllers/security/create-api-key/snippets/create-api-key.js
  doc/7/controllers/security/create-api-key/snippets/create-api-key.test.yml
  doc/7/controllers/security/delete-api-key/index.md
  doc/7/controllers/security/delete-api-key/snippets/delete-api-key.js
  doc/7/controllers/security/delete-api-key/snippets/delete-api-key.test.yml
  doc/7/controllers/security/search-api-keys/index.md
  doc/7/controllers/security/search-api-keys/snippets/search-api-keys.js
  doc/7/controllers/security/search-api-keys/snippets/search-api-keys.test.yml
  features/steps/document.js
  src/Kuzzle.js
  src/controllers/auth.js
  src/controllers/security/index.js
  test/controllers/auth.test.js
  test/controllers/security.test.js
  test/kuzzle/query.test.js
Labels: 7-dev, changelog:new-features

#479 Add a "source" option for document:update to retrieve the updated document
  doc/7/controllers/document/update/index.md
  src/controllers/document.js
  test/controllers/document.test.js
Labels: 7-dev, changelog:enhancements

#483 Migrate the ci (v6) to use KuzDoc
  .travis.yml
  doc/doc.sh
  package-lock.json
  package.json
Labels: changelog:exclude

#482 Migrate the CI (V7) to use KuzDoc
  .travis.yml
  doc/7/core-classes/kuzzle/introduction/index.md
  doc/doc.sh
  package-lock.json
  package.json
Labels: changelog:exclude

#484 Fix protocol port option
  src/protocols/abstract/common.js
  test/protocol/common.test.js
Labels: 7-dev

#481 Add readme and snippets to the React Native getting started
  doc/7/getting-started/.react-native/App.js
  doc/7/getting-started/.react-native/screens/Chat/ChatClient.js
  doc/7/getting-started/.react-native/screens/Chat/ChatView.js
  doc/7/getting-started/.react-native/screens/Login/Login.js
  doc/7/getting-started/react-native/index.md
  doc/7/getting-started/react-native/snippets/App.js.snippet
  doc/7/getting-started/react-native/snippets/ChatClient.js.snippet
  doc/7/getting-started/react-native/snippets/ChatView.js.snippet
  doc/7/getting-started/react-native/snippets/Login.js.snippet
  doc/7/getting-started/react-native/snippets/kuzzle.js.snippet
Labels: 7-dev

#486 Fix ES website deadlink for v7
  doc/7/controllers/collection/create/index.md
Labels: changelog:exclude

#487 Fix ES website deadlink for v6
  doc/6/controllers/collection/create/index.md
Labels: changelog:exclude

#488 Fix ES website deadlink for v5
  doc/5/core-classes/collection-mapping/constructor/index.md
  doc/5/core-classes/collection/create/index.md
Labels: changelog:exclude
