Repository kuzzleio/sdk-javascript, pull requests merged in 2020-02, with the labels that each got.

#490 Throw an error when an URL param is missing in HTTP
  doc/7/controllers/server/get-all-stats/snippets/get-all-stats.test.yml
  doc/7/controllers/server/get-last-stats/snippets/get-last-stats.test.yml
  doc/7/controllers/server/get-stats/snippets/get-stats.test.yml
  doc/7/controllers/server/info/snippets/info.test.yml
  doc/7/controllers/server/now/snippets/now.test.yml
  src/protocols/http.js
  test/protocol/http.test.js
Labels: 7-dev, changelog:bug-fixes

#465 Choose GET route by default in case of double route
  doc/7/controllers/document/m-get/index.md
  doc/7/controllers/security/m-get-users/index.md
  doc/7/controllers/security/m-get-users/snippets/m-get-users.js
  doc/7/controllers/security/m-get-users/snippets/m-get-users.test.yml
  doc/7/controllers/server/get-all-stats/snippets/get-all-stats.test.yml
  src/Kuzzle.js
  src/controllers/auth.js
  src/controllers/document.js
  src/controllers/security/index.js
  src/protocols/abstract/common.js
  src/protocols/http.js
  test/controllers/auth.test.js
  test/controllers/document.test.js
  test/protocol/http.test.js
Labels: 7-dev, changelog:enhancements

#480 Add React Native getting started
  .ci/test-docs.sh
  doc/7/getting-started/.react-native/.expo-shared/assets.json
  doc/7/getting-started/.react-native/.gitignore
  doc/7/getting-started/.react-native/App.js
  doc/7/getting-started/.react-native/app.json
  doc/7/getting-started/.react-native/assets/icon.png
  doc/7/getting-started/.react-native/assets/splash.png
  doc/7/getting-started/.react-native/babel.config.js
  doc/7/getting-started/.react-native/cypress.json
  doc/7/getting-started/.react-native/cypress/fixtures/Elrond.json
  doc/7/getting-started/.react-native/cypress/fixtures/Legolas.json
  doc/7/getting-started/.react-native/cypress/fixtures/Sam.json
  doc/7/getting-started/.react-native/cypress/fixtures/Sauron.json
  doc/7/getting-started/.react-native/cypress/integration/react-native-chat.spec.js
  doc/7/getting-started/.react-native/cypress/plugins/index.js
  doc/7/getting-started/.react-native/cypress/support/commands.js
  doc/7/getting-started/.react-native/cypress/support/index.js
  doc/7/getting-started/.react-native/package-lock.json
  doc/7/getting-started/.react-native/package.json
  doc/7/getting-started/.react-native/screens/Chat/ChatClient.js
  doc/7/getting-started/.react-native/screens/Chat/ChatView.js
  doc/7/getting-started/.react-native/screens/Login/Login.js
  doc/7/getting-started/.react-native/services/kuzzle.js
  doc/7/getting-started/.react/cypress/integration/react-chat.spec.js
  doc/7/getting-started/.react/package-lock.json
  doc/7/getting-started/.vuejs/cypress/integration/vue-chat.spec.js
  doc/7/getting-started/react-native/index.md
  doc/7/getting-started/react-native/snippets/App.js.snippet
  doc/7/getting-started/react-native/snippets/ChatClient.js.snippet
  doc/7/getting-started/react-native/snippets/ChatView.js.snippet
  doc/7/getting-started/react-native/snippets/Login.js.snippet
  doc/7/getting-started/react-native/snippets/kuzzle.js.snippet
Labels: 7-dev
