Repository kuzzleio/sdk-javascript, pull requests merged in 2020-06, with the labels that each got.

#519 Add document:updateByQuery
  .ci/doc/templates/print-result-successes.tpl.js
  doc/7/controllers/document/update-by-query/index.md
  doc/7/controllers/document/update-by-query/snippets/update-by-query.js
  doc/7/controllers/document/update-by-query/snippets/update-by-query.test.yml
  package-lock.json
  package.json
  src/controllers/Document.js
  src/protocols/routes.json
  test/controllers/document.test.js
Labels: 7-dev, changelog:new-features

#514 Able to execute document search as GET http method
  doc/7/controllers/document/search/index.md
  package-lock.json
  package.json
  src/controllers/Document.js
  src/protocols/Http.js
  src/protocols/WebSocket.js
  src/protocols/abstract/Base.js
  src/protocols/routes.json
  test/controllers/document.test.js
  test/protocol/Http.test.js
Labels: 7-dev, changelog:enhancements

#522 Add bulk:deleteByQuery
  doc/7/controllers/bulk/delete-by-query/index.md
  doc/7/controllers/bulk/delete-by-query/snippets/delete-by-query.js
  doc/7/controllers/bulk/delete-by-query/snippets/delete-by-query.test.yml
  src/controllers/Bulk.js
  src/protocols/routes.json
  test/controllers/bulk.test.js
Labels: 7-dev, changelog:new-features

#520 Hide kuzzle object from console.log
  doc/7/controllers/security/m-get-profiles/snippets/m-get-profiles.test.yml
  doc/7/controllers/security/m-get-roles/snippets/m-get-roles.test.yml
  doc/7/controllers/security/m-get-users/snippets/m-get-users.test.yml
  src/controllers/Base.js
  src/controllers/MemoryStorage.js
  src/controllers/Realtime.js
  src/controllers/Security.js
  src/core/KuzzleEventEmitter.js
  src/core/Room.js
  src/core/searchResult/SearchResultBase.js
  src/core/security/Profile.js
  src/core/security/Role.js
  src/core/security/User.js
  test/controllers/realtime.test.js
  test/controllers/security.test.js
  test/core/room.test.js
Labels: 7-dev, changelog:exclude

#524 Support ms:mexecute
  doc/7/controllers/ms/mexecute/index.md
  doc/7/controllers/ms/mexecute/snippets/mexecute.js
  doc/7/controllers/ms/mexecute/snippets/mexecute.test.yml
  src/controllers/MemoryStorage.js
  src/protocols/routes.json
  test/controllers/memoryStorage.test.js
Labels: 7-dev, changelog:new-features
