Repository kuzzleio/sdk-javascript, pull requests merged in 2021-02, with the labels that each got.

#602 Fix re-subscription
  doc/7/essentials/events/index.md
  src/Kuzzle.ts
  src/protocols/WebSocket.ts
  src/protocols/abstract/Base.ts
  test/kuzzle/connect.test.js
  test/kuzzle/protocol.test.js
  test/kuzzle/query.test.js
  test/protocol/WebSocket.test.js
Labels: 7-dev, changelog:bug-fixes

#586 Add keep-alive mechanism to detect connection lost with realtime protocols
  .ci/doc/docker-compose.yml
  .ci/doc/templates/blank.tpl.js
  .ci/doc/templates/catch.tpl.js
  .ci/doc/templates/createDocumentAfterSnippet.tpl.js
  .ci/doc/templates/default.tpl.js
  .ci/doc/templates/print-result-successes.tpl.js
  .ci/doc/templates/realtime.tpl.js
  .ci/doc/templates/success.tpl.js
  .ci/doc/templates/thencatch.tpl.js
  .ci/doc/templates/without-connect.tpl.js
  doc/7/controllers/ms/geopos/snippets/geopos.test.yml
  doc/7/controllers/ms/georadius/snippets/georadius.test.yml
  doc/7/controllers/ms/georadiusbymember/snippets/georadiusbymember.test.yml
  doc/7/controllers/ms/hscan/snippets/hscan.test.yml
  doc/7/controllers/ms/sort/snippets/sort.test.yml
  doc/7/controllers/ms/sunion/snippets/sunion.test.yml
  doc/7/controllers/ms/sunionstore/snippets/sunionstore.test.yml
  doc/7/controllers/ms/zadd/snippets/zadd.test.yml
  doc/7/controllers/ms/zincrby/snippets/zincrby.test.yml
  doc/7/controllers/ms/zinterstore/snippets/zinterstore.test.yml
  doc/7/controllers/ms/zrange/snippets/zrange.test.yml
  doc/7/controllers/ms/zrangebyscore/snippets/zrangebyscore.test.yml
  doc/7/controllers/ms/zrevrangebyscore/snippets/zrevrangebyscore.test.yml
  doc/7/controllers/ms/zscan/snippets/zscan.test.yml
  doc/7/controllers/ms/zunionstore/snippets/zunionstore.test.yml
  doc/7/controllers/security/create-user/snippets/create-user.js
  doc/7/controllers/security/create-user/snippets/create-user.test.yml
  doc/7/controllers/security/get-profile-mapping/snippets/get-profile-mapping.test.yml
  doc/7/controllers/security/get-profile-rights/snippets/get-profile-rights.test.yml
  doc/7/controllers/security/get-profile/snippets/get-profile.test.yml
  doc/7/controllers/security/get-role-mapping/snippets/get-role-mapping.test.yml
  doc/7/controllers/security/get-role/snippets/get-role.test.yml
  doc/7/controllers/security/get-user-mapping/snippets/get-user-mapping.test.yml
  doc/7/controllers/security/get-user-rights/snippets/get-user-rights.test.yml
  doc/7/controllers/security/get-user/snippets/get-user.test.yml
  doc/7/controllers/security/replace-user/snippets/replace-user.test.yml
  doc/7/controllers/security/update-profile/snippets/update-profile.test.yml
  doc/7/controllers/security/update-role/snippets/update-role.test.yml
  doc/7/controllers/security/update-user/snippets/update-user.test.yml
  doc/7/protocols/websocket/constructor/index.md
  doc/7/protocols/websocket/introduction/index.md
  doc/7/protocols/websocket/properties/index.md
  src/controllers/Auth.ts
  src/protocols/WebSocket.ts
  src/protocols/abstract/Realtime.ts
  test/protocol/WebSocket.test.js
Labels: 7-dev, changelog:enhancements, release-kuzzle-2.10

#603 Release 7.5.4
  .ci/doc/docker-compose.yml
  .ci/doc/templates/blank.tpl.js
  .ci/doc/templates/catch.tpl.js
  .ci/doc/templates/createDocumentAfterSnippet.tpl.js
  .ci/doc/templates/default.tpl.js
  .ci/doc/templates/print-result-successes.tpl.js
  .ci/doc/templates/realtime.tpl.js
  .ci/doc/templates/success.tpl.js
  .ci/doc/templates/thencatch.tpl.js
  .ci/doc/templates/without-connect.tpl.js
  doc/7/controllers/ms/geopos/snippets/geopos.test.yml
  doc/7/controllers/ms/georadius/snippets/georadius.test.yml
  doc/7/controllers/ms/georadiusbymember/snippets/georadiusbymember.test.yml
  doc/7/controllers/ms/hscan/snippets/hscan.test.yml
  doc/7/controllers/ms/sort/snippets/sort.test.yml
  doc/7/controllers/ms/sunion/snippets/sunion.test.yml
  doc/7/controllers/ms/sunionstore/snippets/sunionstore.test.yml
  doc/7/controllers/ms/zadd/snippets/zadd.test.yml
  doc/7/controllers/ms/zincrby/snippets/zincrby.test.yml
  doc/7/controllers/ms/zinterstore/snippets/zinterstore.test.yml
  doc/7/controllers/ms/zrange/snippets/zrange.test.yml
  doc/7/controllers/ms/zrangebyscore/snippets/zrangebyscore.test.yml
  doc/7/controllers/ms/zrevrangebyscore/snippets/zrevrangebyscore.test.yml
  doc/7/controllers/ms/zscan/snippets/zscan.test.yml
  doc/7/controllers/ms/zunionstore/snippets/zunionstore.test.yml
  doc/7/controllers/security/create-user/snippets/create-user.js
  doc/7/controllers/security/create-user/snippets/create-user.test.yml
  doc/7/controllers/security/get-profile-mapping/snippets/get-profile-mapping.test.yml
  doc/7/controllers/security/get-profile-rights/snippets/get-profile-rights.test.yml
  doc/7/controllers/security/get-profile/snippets/get-profile.test.yml
  doc/7/controllers/security/get-role-mapping/snippets/get-role-mapping.test.yml
  doc/7/controllers/security/get-role/snippets/get-role.test.yml
  doc/7/controllers/security/get-user-mapping/snippets/get-user-mapping.test.yml
  doc/7/controllers/security/get-user-rights/snippets/get-user-rights.test.yml
  doc/7/controllers/security/get-user/snippets/get-user.test.yml
  doc/7/controllers/security/replace-user/snippets/replace-user.test.yml
  doc/7/controllers/security/update-profile/snippets/update-profile.test.yml
  doc/7/controllers/security/update-role/snippets/update-role.test.yml
  doc/7/controllers/security/update-user/snippets/update-user.test.yml
  doc/7/essentials/events/index.md
  doc/7/protocols/websocket/constructor/index.md
  doc/7/protocols/websocket/introduction/index.md
  doc/7/protocols/websocket/properties/index.md
  package-lock.json
  package.json
  src/Kuzzle.ts
  src/controllers/Auth.ts
  src/protocols/WebSocket.ts
  src/protocols/abstract/Base.ts
  src/protocols/abstract/Realtime.ts
  test/kuzzle/connect.test.js
  test/kuzzle/protocol.test.js
  test/kuzzle/query.test.js
  test/protocol/WebSocket.test.js
Labels: release

#605 [HOTFIX] Check client readyState before sending pings
  package-lock.json
  package.json
  src/protocols/WebSocket.ts
  src/protocols/abstract/Realtime.ts
Labels: 7-dev, changelog:bug-fixes

#607 [HOTFIX] Clear PingTimeout
  package-lock.json
  package.json
  src/protocols/WebSocket.ts
  src/protocols/abstract/Realtime.ts
  test/protocol/WebSocket.test.js
Labels: 7-dev, changelog:bug-fixes
