Repository kuzzleio/sdk-javascript, pull requests merged in 2021-09, with the labels that each got.

#661 Allows to define custom headers for HTTP protocol
  doc/7/protocols/http/constructor/index.md
  doc/7/protocols/http/constructor/snippets/constructor.js
  src/protocols/Http.ts
  test/protocol/Http.test.js
Labels: changelog:enhancements

#660 Fix upsert options.default
  doc/7/controllers/document/upsert/index.md
  src/controllers/Document.ts
  test/controllers/document.test.js
Labels: changelog:bug-fixes, 7-dev

#662 Release 7.7.5
  doc/7/controllers/document/upsert/index.md
  doc/7/protocols/http/constructor/index.md
  doc/7/protocols/http/constructor/snippets/constructor.js
  package-lock.json
  package.json
  src/controllers/Document.ts
  src/protocols/Http.ts
  test/controllers/document.test.js
  test/protocol/Http.test.js
Labels: release

#664 Fix reconnectionError not emittend when authenticator is missing
  src/Kuzzle.ts
  test/kuzzle/authenticator.test.js
Labels: changelog:bug-fixes
