Repository kuzzleio/sdk-javascript, pull requests merged in 2021-05, with the labels that each got.

#635 Fix cookie authentication support for WebSocket
  doc/7/core-classes/kuzzle/constructor/index.md
  package-lock.json
  package.json
  src/protocols/WebSocket.ts
  test/protocol/WebSocket.test.js
Labels: 7-dev, changelog:bug-fixes

#636 Add support for the document:deleteFields API action
  doc/7/controllers/document/delete-fields/index.md
  doc/7/controllers/document/delete-fields/snippets/deleteFields.js
  doc/7/controllers/document/delete-fields/snippets/deleteFields.test.yml
  src/controllers/Document.ts
  test/controllers/document.test.js
Labels: 7-dev, changelog:new-features

#639 Add an origin parameter to the kuzzle disconnected event
  doc/7/essentials/events/index.md
  src/Kuzzle.ts
  src/protocols/DisconnectionOrigin.ts
  src/protocols/WebSocket.ts
  src/protocols/abstract/Realtime.ts
  test/mocks/protocol.mock.js
  test/protocol/WebSocket.test.js
Labels: 7-dev, changelog:new-features

#642 Release 7.7.1
  .github/workflows/pull_request.workflow.yml
  .github/workflows/push_master.workflow.yml
  doc/7/controllers/bulk/update-by-query/index.md
  doc/7/controllers/bulk/update-by-query/snippets/update-by-query.js
  doc/7/controllers/bulk/update-by-query/snippets/update-by-query.test.yml
  doc/7/controllers/document/m-upsert/index.md
  doc/7/controllers/document/m-upsert/snippets/m-upsert.js
  doc/7/controllers/document/m-upsert/snippets/m-upsert.test.yml
  package-lock.json
  package.json
  src/controllers/Bulk.ts
  src/controllers/Document.ts
  src/protocols/routes.json
Labels: release
