Repository kuzzleio/sdk-javascript, pull requests merged in 2021-07, with the labels that each got.

#646 Fix usage of SearchResult.next with HTTP
  src/core/searchResult/SearchResultBase.ts
  test/core/searchResult/document.test.js
  test/core/searchResult/profile.test.js
  test/core/searchResult/specifications.test.js
  test/core/searchResult/user.test.js
Labels: 7-dev, changelog:bug-fixes

#648 Fix the Jwt.expired getter wrong comparison of micro timestamp and timestamp
  src/core/Jwt.js
  test/core/Jwt.test.js
  test/mocks/generateJwt.mock.js
Labels: 7-dev, changelog:bug-fixes

#651 Hotfix heartbeat race condition
  src/protocols/WebSocket.ts
  test/protocol/WebSocket.test.js
Labels: changelog:bug-fixes

#649 Re activate AC tests and Trigger doc workflows
  .github/actions/dead-links/action.yml
  .github/actions/doc-deploy/action.yml
  .github/actions/tests-ac/action.yml
  .github/workflows/pull_request.workflow.yml
  .github/workflows/push_dev.workflow.yml
  .github/workflows/push_master.workflow.yml
  .gitignore
Labels: changelog:exclude

#652 Release 7.7.2
  .eslintignore
  .github/actions/dead-links/action.yml
  .github/actions/doc-deploy/action.yml
  .github/actions/tests-ac/action.yml
  .github/workflows/pull_request.workflow.yml
  .github/workflows/push_dev.workflow.yml
  .github/workflows/push_master.workflow.yml
  .gitignore
  doc/7/core-classes/kuzzle/authenticate/index.md
  doc/7/core-classes/kuzzle/authenticate/snippets/authenticate.js
  doc/7/core-classes/kuzzle/authenticate/snippets/authenticate.test.yml
  doc/7/core-classes/kuzzle/properties/index.md
  doc/7/essentials/offline-tools/index.md
  package-lock.json
  package.json
  src/Kuzzle.ts
  src/core/Jwt.js
  src/core/searchResult/SearchResultBase.ts
  src/protocols/WebSocket.ts
  test/core/Jwt.test.js
  test/core/searchResult/document.test.js
  test/core/searchResult/profile.test.js
  test/core/searchResult/specifications.test.js
  test/core/searchResult/user.test.js
  test/kuzzle/authenticator.test.js
  test/kuzzle/listenersManagement.test.js
  test/kuzzle/queue.test.js
  test/mocks/generateJwt.mock.js
  test/protocol/WebSocket.test.js
Labels: release
