Repository kuzzleio/sdk-javascript, pull requests merged in 2021-04, with the labels that each got.

#621 Secure WebSocket connection with cookie authentication
  doc/7/core-classes/kuzzle/constructor/index.md
  doc/7/protocols/websocket/introduction/index.md
  doc/7/protocols/websocket/introduction/websocket-cookie-authentication.png
  src/Kuzzle.ts
  src/protocols/Http.ts
  src/protocols/WebSocket.ts
  src/protocols/abstract/Base.ts
  test/kuzzle/constructor.test.js
  test/mocks/protocol.mock.js
  test/protocol/Http.test.js
  test/protocol/WebSocket.test.js
Labels: 7-dev, changelog:new-features

#624 Release 7.6.0
  .eslintignore
  .gitignore
  doc/7/controllers/index/stats/index.md
  doc/7/controllers/index/stats/snippets/stats.js
  doc/7/controllers/index/stats/snippets/stats.test.yml
  doc/7/controllers/security/create-user/snippets/create-user.test.yml
  doc/7/controllers/security/get-user-strategies/index.md
  doc/7/controllers/security/get-user-strategies/snippets/get-user-strategies.js
  doc/7/controllers/security/get-user-strategies/snippets/get-user-strategies.test.yml
  doc/7/core-classes/kuzzle-error/properties/index.md
  doc/7/core-classes/kuzzle/constructor/index.md
  doc/7/core-classes/search-result/properties/index.md
  doc/7/core-classes/user/properties/index.md
  doc/7/essentials/error-handling/index.md
  doc/7/protocols/websocket/introduction/index.md
  doc/7/protocols/websocket/introduction/websocket-cookie-authentication.png
  package-lock.json
  package.json
  src/Kuzzle.ts
  src/KuzzleError.ts
  src/controllers/Base.ts
  src/controllers/Index.ts
  src/controllers/Security.js
  src/core/searchResult/Document.ts
  src/core/searchResult/Profile.ts
  src/core/searchResult/Role.ts
  src/core/searchResult/SearchResultBase.ts
  src/core/searchResult/Specifications.ts
  src/core/searchResult/User.ts
  src/core/security/User.ts
  src/protocols/Http.ts
  src/protocols/WebSocket.ts
  src/protocols/abstract/Base.ts
  src/protocols/routes.json
  src/types/ResponsePayload.ts
  src/utils/Deprecation.ts
  test/controllers/collection.test.js
  test/controllers/document.test.js
  test/controllers/index.test.js
  test/controllers/security.test.js
  test/core/searchResult/document.test.js
  test/core/searchResult/profile.test.js
  test/core/searchResult/role.test.js
  test/core/searchResult/specifications.test.js
  test/core/searchResult/user.test.js
  test/core/security/user.test.js
  test/kuzzle/constructor.test.js
  test/kuzzle/query.test.js
  test/mocks/protocol.mock.js
  test/protocol/Http.test.js
  test/protocol/WebSocket.test.js
  test/utils/Deprecation.test.js
  webpack.config.js
Labels: release

#625 Fix non relative import
  .github/actions/tests-ac/action.yml
  .github/workflows/pull_request.workflow.yml
  .github/workflows/push_dev.workflow.yml
  .github/workflows/push_master.workflow.yml
  package-lock.json
  package.json
  src/utils/Deprecation.ts
Labels: changelog:bug-fixes

#630 [HOTFIX] Ensure returning the user body in the content property when serialized
  doc/7/core-classes/profile/serialize/index.md
  doc/7/core-classes/role/serialize/index.md
  doc/7/core-classes/user/serialize/index.md
  package-lock.json
  package.json
  src/controllers/Document.ts
  src/core/security/Profile.ts
  src/core/security/Role.ts
  src/core/security/User.ts
Labels: 7-dev, changelog:bug-fixes

#626 Remove mentions of admin console tests in workflow
  .github/workflows/push_master.workflow.yml
Labels: changelog:exclude

#634 docs: use index from callback argument instead of indexOf
  doc/7/getting-started/.react/with-redux/src/App.js
Labels: 7-dev, changelog:exclude
