Repository kuzzleio/sdk-javascript, pull requests merged in 2021-03, with the labels that each got.

#606 Add _source property to user objects
  doc/7/controllers/security/create-user/snippets/create-user.test.yml
  doc/7/core-classes/user/properties/index.md
  src/core/security/User.ts
  test/core/security/user.test.js
Labels: 7-dev, changelog:enhancements

#612 Implement security:getUserStrategies
  doc/7/controllers/security/get-user-strategies/index.md
  doc/7/controllers/security/get-user-strategies/snippets/get-user-strategies.js
  doc/7/controllers/security/get-user-strategies/snippets/get-user-strategies.test.yml
  src/controllers/Security.js
  src/protocols/routes.json
  test/controllers/security.test.js
Labels: 7-dev, changelog:new-features

#610 Add cookie authentication support
  doc/7/controllers/auth/login/index.md
  doc/7/controllers/auth/refresh-token/index.md
  doc/7/core-classes/kuzzle/constructor/index.md
  src/Kuzzle.ts
  src/controllers/Auth.ts
  src/protocols/Http.ts
  test/controllers/auth.test.js
Labels: 7-dev, changelog:new-features

#614 Print deprecation warning from Kuzzle
  doc/7/core-classes/kuzzle/constructor/index.md
  src/Kuzzle.ts
  src/controllers/Base.ts
  src/types/ResponsePayload.ts
  src/utils/Deprecation.ts
  test/kuzzle/query.test.js
  test/utils/Deprecation.test.js
Labels: changelog:new-features

#617 Add suggest to search result
  doc/7/core-classes/search-result/properties/index.md
  package-lock.json
  package.json
  src/core/searchResult/Document.ts
  src/core/searchResult/Profile.ts
  src/core/searchResult/Role.ts
  src/core/searchResult/SearchResultBase.ts
  src/core/searchResult/Specifications.ts
  src/core/searchResult/User.ts
  test/controllers/collection.test.js
  test/controllers/document.test.js
  test/controllers/security.test.js
  test/core/searchResult/document.test.js
  test/core/searchResult/profile.test.js
  test/core/searchResult/role.test.js
  test/core/searchResult/specifications.test.js
  test/core/searchResult/user.test.js
  webpack.config.js
Labels: 7-dev, changelog:enhancements

#613 Implement index:stats
  doc/7/controllers/index/stats/index.md
  doc/7/controllers/index/stats/snippets/stats.js
  doc/7/controllers/index/stats/snippets/stats.test.yml
  src/controllers/Index.ts
  test/controllers/index.test.js
Labels: 7-dev, changelog:new-features

#618 Update our CONTRIBUTING templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: changelog:exclude

#620 Add kuzzleStack property to KuzzleError
  doc/7/core-classes/kuzzle-error/properties/index.md
  doc/7/essentials/error-handling/index.md
  src/KuzzleError.ts
Labels: 7-dev, changelog:enhancements

#622 Pick first route when multiple non-GET routes of the same size are available
  .eslintignore
  src/protocols/Http.ts
  test/protocol/Http.test.js
Labels: 7-dev, changelog:bug-fixes
