Repository kuzzleio/sdk-javascript, pull requests merged in 2021-08, with the labels that each got.

#653 Reconnect with authenticator when receiving TokenExpired event
  doc/7/getting-started/.vuejs/package-lock.json
  doc/7/getting-started/.vuejs/package.json
  package-lock.json
  src/Kuzzle.ts
  src/controllers/Auth.ts
  src/controllers/Realtime.ts
  src/protocols/WebSocket.ts
  src/protocols/abstract/Realtime.ts
  test/kuzzle/authenticator.test.js
  test/kuzzle/listenersManagement.test.js
  test/protocol/WebSocket.test.js
Labels: changelog:enhancements, 7-dev

#656 Release 7.7.3
  doc/7/getting-started/.react-native/package-lock.json
  doc/7/getting-started/.react-native/package.json
  doc/7/getting-started/.vuejs/package-lock.json
  doc/7/getting-started/.vuejs/package.json
  package-lock.json
  package.json
  src/Kuzzle.ts
  src/controllers/Auth.ts
  src/controllers/Realtime.ts
  src/protocols/WebSocket.ts
  src/protocols/abstract/Realtime.ts
  test/kuzzle/authenticator.test.js
  test/kuzzle/listenersManagement.test.js
  test/protocol/WebSocket.test.js
Labels: release

#657 Automatic resubscription when logged in using jwt property
  src/Kuzzle.ts
  test/kuzzle/authenticator.test.js
  test/kuzzle/protocol.test.js
Labels: changelog:enhancements

#658 Resubscription not working in the browser because of a bad transpilation
  src/controllers/Realtime.ts
Labels: changelog:bug-fixes

#659 Release 7.7.4
  package-lock.json
  package.json
  src/Kuzzle.ts
  src/controllers/Realtime.ts
  test/kuzzle/authenticator.test.js
  test/kuzzle/protocol.test.js
Labels: release
