Repository kuzzleio/sdk-javascript, pull requests merged in 2021-01, with the labels that each got.

#575 Support "lang" parameter for Koncorde filters
  doc/7/controllers/auth/search-api-keys/index.md
  doc/7/controllers/auth/search-api-keys/snippets/search-api-keys-es.js
  doc/7/controllers/auth/search-api-keys/snippets/search-api-keys-es.test.yml
  doc/7/controllers/auth/search-api-keys/snippets/search-api-keys-koncorde.js
  doc/7/controllers/auth/search-api-keys/snippets/search-api-keys-koncorde.test.yml
  doc/7/controllers/bulk/delete-by-query/snippets/delete-by-query.test.yml
  doc/7/controllers/document/delete-by-query/index.md
  doc/7/controllers/document/delete-by-query/snippets/delete-by-query-es.js
  doc/7/controllers/document/delete-by-query/snippets/delete-by-query-es.test.yml
  doc/7/controllers/document/delete-by-query/snippets/delete-by-query-koncorde.js
  doc/7/controllers/document/delete-by-query/snippets/delete-by-query-koncorde.test.yml
  doc/7/controllers/document/search/index.md
  doc/7/controllers/document/search/snippets/search-es.js
  doc/7/controllers/document/search/snippets/search-es.test.yml
  doc/7/controllers/document/search/snippets/search-koncorde.js
  doc/7/controllers/document/search/snippets/search-koncorde.test.yml
  doc/7/controllers/document/update-by-query/index.md
  doc/7/controllers/document/update-by-query/snippets/update-by-query-es.js
  doc/7/controllers/document/update-by-query/snippets/update-by-query-es.test.yml
  doc/7/controllers/document/update-by-query/snippets/update-by-query-koncorde.js
  doc/7/controllers/document/update-by-query/snippets/update-by-query-koncorde.test.yml
  doc/7/controllers/security/create-first-admin/index.md
  doc/7/controllers/security/create-restricted-user/index.md
  doc/7/controllers/security/create-user/index.md
  doc/7/controllers/security/get-user/index.md
  doc/7/controllers/security/replace-user/index.md
  doc/7/controllers/security/search-api-keys/index.md
  doc/7/controllers/security/search-api-keys/snippets/search-api-keys-es.js
  doc/7/controllers/security/search-api-keys/snippets/search-api-keys-es.test.yml
  doc/7/controllers/security/search-api-keys/snippets/search-api-keys-koncorde.js
  doc/7/controllers/security/search-api-keys/snippets/search-api-keys-koncorde.test.yml
  doc/7/controllers/security/search-profiles/index.md
  doc/7/controllers/security/search-roles/index.md
  doc/7/controllers/security/search-users/index.md
  doc/7/controllers/security/search-users/snippets/search-users-es.js
  doc/7/controllers/security/search-users/snippets/search-users-es.test.yml
  doc/7/controllers/security/search-users/snippets/search-users-koncorde.js
  doc/7/controllers/security/search-users/snippets/search-users-koncorde.test.yml
  doc/7/controllers/security/update-user/index.md
  src/controllers/Auth.ts
  src/controllers/Document.ts
  src/controllers/Security.js
  test/controllers/auth.test.js
  test/controllers/document.test.js
  test/controllers/security.test.js
Labels: 7-dev, changelog:new-features

#576 Add document:upsert
  doc/7/controllers/document/upsert/index.md
  doc/7/controllers/document/upsert/snippets/upsert.js
  doc/7/controllers/document/upsert/snippets/upsert.test.yml
  src/Kuzzle.ts
  src/controllers/Document.ts
  src/types/Document.ts
Labels: 7-dev, changelog:new-features

#577 Add [auth|security]:checkRights
  doc/7/controllers/auth/check-rights/index.md
  doc/7/controllers/auth/check-rights/snippets/check-rights.js
  doc/7/controllers/auth/check-rights/snippets/check-rights.test.yml
  doc/7/controllers/security/check-rights/index.md
  doc/7/controllers/security/check-rights/snippets/check-rights.js
  doc/7/controllers/security/check-rights/snippets/check-rights.test.yml
  src/controllers/Auth.ts
  src/controllers/Security.js
Labels: 7-dev, changelog:new-features

#584 Fix typo documentation
  doc/7/controllers/auth/create-api-key/index.md
  doc/7/controllers/auth/create-api-key/snippets/create-api-key.test.yml
  doc/7/controllers/auth/delete-api-key/index.md
  doc/7/controllers/auth/delete-api-key/snippets/delete-api-key.test.yml
  doc/7/controllers/auth/search-api-keys/index.md
  doc/7/controllers/auth/search-api-keys/snippets/search-api-keys-es.test.yml
  doc/7/controllers/auth/search-api-keys/snippets/search-api-keys-koncorde.test.yml
  src/controllers/Auth.ts
Labels: changelog:exclude

#588 Release 7.5.0
  doc/7/controllers/auth/check-rights/index.md
  doc/7/controllers/auth/check-rights/snippets/check-rights.js
  doc/7/controllers/auth/check-rights/snippets/check-rights.test.yml
  doc/7/controllers/document/upsert/index.md
  doc/7/controllers/document/upsert/snippets/upsert.js
  doc/7/controllers/document/upsert/snippets/upsert.test.yml
  doc/7/controllers/security/check-rights/index.md
  doc/7/controllers/security/check-rights/snippets/check-rights.js
  doc/7/controllers/security/check-rights/snippets/check-rights.test.yml
  package-lock.json
  package.json
  src/Kuzzle.ts
  src/controllers/Auth.ts
  src/controllers/Document.ts
  src/controllers/Security.js
  src/types/Document.ts
Labels: release

#589 [Hotfix] Fix type MappingProperties
  package-lock.json
  package.json
  src/types/Mappings.ts
Labels: 7-dev, changelog:bug-fixes

#590 [HOTFIX] relative import in Auth.ts
  package-lock.json
  package.json
  src/controllers/Auth.ts
Labels: changelog:bug-fixes

#595 Allows to not send realtime notification on document controller
  doc/7/controllers/document/create-or-replace/index.md
  doc/7/controllers/document/create/index.md
  doc/7/controllers/document/delete-by-query/index.md
  doc/7/controllers/document/delete/index.md
  doc/7/controllers/document/m-create-or-replace/index.md
  doc/7/controllers/document/m-create/index.md
  doc/7/controllers/document/m-delete/index.md
  doc/7/controllers/document/m-replace/index.md
  doc/7/controllers/document/m-update/index.md
  doc/7/controllers/document/replace/index.md
  doc/7/controllers/document/update-by-query/index.md
  doc/7/controllers/document/update/index.md
  doc/7/controllers/document/upsert/index.md
  src/Kuzzle.ts
  src/controllers/Document.ts
  test/controllers/document.test.js
Labels: 7-dev, changelog:enhancements

#598 Release 7.5.3
  .github/actions/dead-links/action.yml
  .github/actions/doc-deploy/action.yml
  .github/actions/es-lint/action.yml
  .github/actions/functional-tests/action.yml
  .github/actions/snippet-tests/action.yml
  .github/actions/tests-ac/action.yml
  .github/actions/unit-tests/action.yml
  .github/workflows/pull_request.workflow.yml
  .github/workflows/push_dev.workflow.yml
  .github/workflows/push_master.workflow.yml
  .travis.yml
  cypress.json
  doc/7/controllers/document/create-or-replace/index.md
  doc/7/controllers/document/create/index.md
  doc/7/controllers/document/delete-by-query/index.md
  doc/7/controllers/document/delete/index.md
  doc/7/controllers/document/m-create-or-replace/index.md
  doc/7/controllers/document/m-create/index.md
  doc/7/controllers/document/m-delete/index.md
  doc/7/controllers/document/m-replace/index.md
  doc/7/controllers/document/m-update/index.md
  doc/7/controllers/document/replace/index.md
  doc/7/controllers/document/update-by-query/index.md
  doc/7/controllers/document/update/index.md
  doc/7/controllers/document/upsert/index.md
  package-lock.json
  package.json
  src/Kuzzle.ts
  src/KuzzleError.ts
  src/controllers/Document.ts
  src/protocols/WebSocket.ts
  src/protocols/abstract/Base.ts
  src/utils/stackTrace.js
  test/controllers/document.test.js
  test/protocol/Base.test.js
Labels: release
