Repository kuzzleio/sdk-javascript, pull requests merged in 2022-04, with the labels that each got.

#693 Add `server:capabilities` method
  index.ts
  src/Kuzzle.ts
  src/controllers/Server.ts
  test/controllers/server.test.js
Labels: changelog:new-features, 7-dev

#692 Add missing strong types in document controller
  src/controllers/Document.ts
Labels: changelog:enhancements

#696 Add `props` in KuzzleError
  doc/7/core-classes/kuzzle-error/properties/index.md
  src/KuzzleError.ts
Labels: changelog:bug-fixes

#695 Fix Bad links in the Kuzzle event documentation
  doc/7/controllers/index.md
  doc/7/core-classes/base-controller/index.md
  doc/7/core-classes/batch-controller/index.md
  doc/7/core-classes/kuzzle-error/index.md
  doc/7/core-classes/kuzzle-event-emitter/index.md
  doc/7/core-classes/kuzzle-event-emitter/introduction/index.md
  doc/7/core-classes/kuzzle/index.md
  doc/7/core-classes/observer/index.md
  doc/7/core-classes/profile/index.md
  doc/7/core-classes/role/index.md
  doc/7/core-classes/search-result/index.md
  doc/7/core-classes/user/index.md
  doc/7/essentials/events/index.md
  doc/7/essentials/index.md
  doc/7/getting-started/index.md
  doc/7/protocols/http/index.md
  doc/7/protocols/index.md
  doc/7/protocols/websocket/index.md
Labels: changelog:exclude
