Repository kuzzleio/sdk-javascript, pull requests merged in 2022-01, with the labels that each got.

#675 Release 7.8.0
  .eslintrc-ts.json
  ast-refactor/inline-options-to-interface.ts
  doc/7/controllers/auth/search-api-keys/snippets/search-api-keys-es.test.yml
  doc/7/controllers/security/get-profile-mapping/snippets/get-profile-mapping.js
  doc/7/controllers/security/get-profile-mapping/snippets/get-profile-mapping.test.yml
  doc/7/controllers/security/search-api-keys/snippets/search-api-keys-es.test.yml
  doc/7/core-classes/observer/get/index.md
  doc/7/core-classes/observer/index.md
  doc/7/core-classes/observer/introduction/index.md
  doc/7/core-classes/observer/m-get/index.md
  doc/7/core-classes/observer/observe/index.md
  doc/7/core-classes/observer/search/index.md
  doc/7/core-classes/observer/stop/index.md
  doc/7/essentials/realtime-application/index.md
  index.ts
  package-lock.json
  package.json
  src/Kuzzle.ts
  src/controllers/Auth.ts
  src/controllers/Bulk.ts
  src/controllers/Collection.ts
  src/controllers/Document.ts
  src/controllers/Index.ts
  src/controllers/Realtime.ts
  src/controllers/Security.ts
  src/controllers/Server.ts
  src/core/Observer.ts
  src/core/RealtimeDocument.ts
  src/core/searchResult/RealtimeDocument.ts
  src/types/ArgsDefault.ts
  src/types/index.ts
  test/core/observer.test.js
  test/kuzzle/query.test.js
Labels: release

#677 Release 7.8.1: Fix bad import
  .github/actions/tests-ac/action.yml
  package-lock.json
  package.json
  src/core/Observer.ts
Labels: changelog:bug-fixes

#669 Add more context to errors
  doc/7/core-classes/kuzzle-error/properties/index.md
  src/KuzzleError.ts
  src/protocols/abstract/Base.ts
  test/protocol/Base.test.js
Labels: changelog:enhancements

#667 Support entire query for security:searchProfiles
  .eslintignore
  .gitignore
  doc/7/controllers/security/m-get-profiles/snippets/m-get-profiles.js
  doc/7/controllers/security/m-get-profiles/snippets/m-get-profiles.test.yml
  doc/7/controllers/security/search-profiles/index.md
  doc/7/controllers/security/search-profiles/snippets/search-profiles.js
  doc/7/controllers/security/search-profiles/snippets/search-profiles.test.yml
  src/controllers/Security.ts
  src/core/Observer.ts
  src/core/security/Profile.ts
  test/controllers/security.test.js
Labels: changelog:enhancements

#681 Release 7.8.2: Fix multiple errors error
  package-lock.json
  package.json
  src/KuzzleError.ts
Labels: changelog:bug-fixes

#676 Add HTTP protocol support for Observer
  doc/7/core-classes/observer/constructor/index.md
  doc/7/core-classes/observer/introduction/index.md
  doc/7/essentials/realtime-application/index.md
  src/Kuzzle.ts
  src/core/Observer.ts
  src/core/searchResult/RealtimeDocument.ts
  src/protocols/abstract/Base.ts
  src/protocols/abstract/Realtime.ts
  test/browser.html
  test/core/observer.test.js
Labels: changelog:enhancements, 7-dev

#678 Improve document search doc
  doc/7/controllers/document/search/index.md
  doc/7/essentials/realtime-application/index.md
Labels: changelog:exclude

#680 Add debug mode
  doc/7/essentials/debugging/index.md
  src/Kuzzle.ts
  src/controllers/Auth.ts
  src/utils/Deprecation.ts
  src/utils/debug.js
Labels: changelog:enhancements

#683 Fix authenticator token verification
  src/Kuzzle.ts
  src/controllers/Auth.ts
Labels: changelog:bug-fixes

#684 Release 7.8.3
  .eslintignore
  .gitignore
  doc/7/controllers/security/m-get-profiles/snippets/m-get-profiles.js
  doc/7/controllers/security/m-get-profiles/snippets/m-get-profiles.test.yml
  doc/7/controllers/security/search-profiles/index.md
  doc/7/controllers/security/search-profiles/snippets/search-profiles.js
  doc/7/controllers/security/search-profiles/snippets/search-profiles.test.yml
  doc/7/core-classes/kuzzle-error/properties/index.md
  doc/7/core-classes/kuzzle/properties/index.md
  doc/7/core-classes/observer/constructor/index.md
  doc/7/core-classes/observer/introduction/index.md
  doc/7/essentials/debugging/index.md
  doc/7/essentials/events/index.md
  doc/7/essentials/realtime-application/index.md
  package-lock.json
  package.json
  src/Kuzzle.ts
  src/KuzzleError.ts
  src/controllers/Auth.ts
  src/controllers/Document.ts
  src/controllers/Security.ts
  src/core/Observer.ts
  src/core/searchResult/RealtimeDocument.ts
  src/core/security/Profile.ts
  src/core/security/User.ts
  src/protocols/abstract/Base.ts
  src/protocols/abstract/Realtime.ts
  src/types/index.ts
  src/types/mRequests.ts
  src/types/mResponses.ts
  src/utils/Deprecation.ts
  src/utils/debug.js
  test/browser.html
  test/controllers/security.test.js
  test/core/observer.test.js
  test/kuzzle/listenersManagement.test.js
  test/protocol/Base.test.js
Labels: release
